### ISSUE TITLE
Error building after adding page

### ISSUE THREAD

**Issue by ss32** [victoriadrake/hugo-theme-quint#4] opened 2024-07-08 11:41 UTC
This could be my inexperience with Hugo but following the same steps with the example theme did not yield any errors.  When building with `hugo server -D` I am met with the following error:

```
Error: Error building site: failed to render pages: render of "page" failed: "/tmp/hugotest/site/themes/quint/layouts/_default/single.html:2:82": execute of template failed: template: _default/single.html:2:82: executing "main" at <math>: can't evaluate field Rand in type interface {}
```

**To Reproduce**

```bash
hugo new site testsite
cd testsite
git init
git submodule add https://github.com/victoriadrake/hugo-theme-quint.git themes/quint
echo "theme = 'quint'" >> config.toml 
hugo new content/posts/test-post.md
echo "testing" >> content/posts/test-post.md
hugo server -D
```

**Expected behavior**
Hugo builds and serves the site

**Additional context**
See the example directory at https://github.com/ss32/hugotest/tree/main/site

**Comment by victoriadrake** [comment] 2024-08-07 19:36
Hello!

Following your steps exactly, I could not reproduce your error. However, the site served only with a "Not found" page.

This is because your set up requires three more steps for Hugo to build your site:

1. Ensure that the test-post.md frontmatter has `draft = false` in order for this page to be built. (Hugo does not build pages marked as drafts.) Rename this file to `index.md` so that Hugo builds this page bundle.
2. Create a `content/index.md` file for Hugo to create the home page.
3. Declare the theme in your `hugo.toml` with `theme = 'quint'`.

These commands will take care of these items:

```
mv content/posts/test-post.md content/posts/index.md

echo "+++
title = 'Test Post'
date = 2024-08-07T14:23:49-05:00
draft = false
+++
testing" > content/posts/index.md

echo "+++
title = 'Test Site'
date = 2024-08-07T14:23:49-05:00
draft = false
+++
testing" > content/index.md

echo "theme = 'quint'" >> hugo.toml
```

If your site still doesn't build with the theme after these changes, please let me know which version of Hugo you are using (run `hugo version`).

**Comment by ganomi46** [comment] 2024-08-20 09:56
I confirm that I had no problem building the site. Great theme. thx

**Comment by victoriadrake** [comment] 2024-08-20 10:20
Great! You're welcome!

**Closed as completed by victoriadrake** 2024-08-20 10:20 UTC
